#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("SimpleTipCalculator.Android.Resource", IsApplication=true)]

namespace SimpleTipCalculator.Android
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Intersoft.Crosslight.Android.Resource.Animation.toast_enter = global::SimpleTipCalculator.Android.Resource.Animation.toast_enter;
			global::Intersoft.Crosslight.Android.Resource.Animation.toast_exit = global::SimpleTipCalculator.Android.Resource.Animation.toast_exit;
			global::Intersoft.Crosslight.Android.Resource.Animation.transition_bottomtop = global::SimpleTipCalculator.Android.Resource.Animation.transition_bottomtop;
			global::Intersoft.Crosslight.Android.Resource.Animation.transition_fadein = global::SimpleTipCalculator.Android.Resource.Animation.transition_fadein;
			global::Intersoft.Crosslight.Android.Resource.Animation.transition_fadeout = global::SimpleTipCalculator.Android.Resource.Animation.transition_fadeout;
			global::Intersoft.Crosslight.Android.Resource.Animation.transition_leftright = global::SimpleTipCalculator.Android.Resource.Animation.transition_leftright;
			global::Intersoft.Crosslight.Android.Resource.Animation.transition_rightleft = global::SimpleTipCalculator.Android.Resource.Animation.transition_rightleft;
			global::Intersoft.Crosslight.Android.Resource.Animation.transition_topbottom = global::SimpleTipCalculator.Android.Resource.Animation.transition_topbottom;
			global::Intersoft.Crosslight.Android.Resource.Array.select_dialog_items3 = global::SimpleTipCalculator.Android.Resource.Array.select_dialog_items3;
			global::Intersoft.Crosslight.Android.Resource.Array.select_image_dialog = global::SimpleTipCalculator.Android.Resource.Array.select_image_dialog;
			global::Intersoft.Crosslight.Android.Resource.Color.bright_foreground_dark = global::SimpleTipCalculator.Android.Resource.Color.bright_foreground_dark;
			global::Intersoft.Crosslight.Android.Resource.Color.listviewbackgroundselector = global::SimpleTipCalculator.Android.Resource.Color.listviewbackgroundselector;
			global::Intersoft.Crosslight.Android.Resource.Drawable.btn_check_off_focused_holo_dark = global::SimpleTipCalculator.Android.Resource.Drawable.btn_check_off_focused_holo_dark;
			global::Intersoft.Crosslight.Android.Resource.Drawable.btn_check_on_pressed_holo_dark = global::SimpleTipCalculator.Android.Resource.Drawable.btn_check_on_pressed_holo_dark;
			global::Intersoft.Crosslight.Android.Resource.Drawable.ic_drawer = global::SimpleTipCalculator.Android.Resource.Drawable.ic_drawer;
			global::Intersoft.Crosslight.Android.Resource.Drawable.leftdrawershadow = global::SimpleTipCalculator.Android.Resource.Drawable.leftdrawershadow;
			global::Intersoft.Crosslight.Android.Resource.Drawable.rightdrawershadow = global::SimpleTipCalculator.Android.Resource.Drawable.rightdrawershadow;
			global::Intersoft.Crosslight.Android.Resource.Drawable.toast_frame_holo = global::SimpleTipCalculator.Android.Resource.Drawable.toast_frame_holo;
			global::Intersoft.Crosslight.Android.Resource.Id.ControlsPlaceholder = global::SimpleTipCalculator.Android.Resource.Id.ControlsPlaceholder;
			global::Intersoft.Crosslight.Android.Resource.Id.DatePickerWidget = global::SimpleTipCalculator.Android.Resource.Id.DatePickerWidget;
			global::Intersoft.Crosslight.Android.Resource.Id.DateTimePickerDateWidget = global::SimpleTipCalculator.Android.Resource.Id.DateTimePickerDateWidget;
			global::Intersoft.Crosslight.Android.Resource.Id.DateTimePickerTimeWidget = global::SimpleTipCalculator.Android.Resource.Id.DateTimePickerTimeWidget;
			global::Intersoft.Crosslight.Android.Resource.Id.EditorContainer = global::SimpleTipCalculator.Android.Resource.Id.EditorContainer;
			global::Intersoft.Crosslight.Android.Resource.Id.FooterLayout = global::SimpleTipCalculator.Android.Resource.Id.FooterLayout;
			global::Intersoft.Crosslight.Android.Resource.Id.FooterText = global::SimpleTipCalculator.Android.Resource.Id.FooterText;
			global::Intersoft.Crosslight.Android.Resource.Id.FormContainer = global::SimpleTipCalculator.Android.Resource.Id.FormContainer;
			global::Intersoft.Crosslight.Android.Resource.Id.HeaderLayout = global::SimpleTipCalculator.Android.Resource.Id.HeaderLayout;
			global::Intersoft.Crosslight.Android.Resource.Id.HeaderSeparator = global::SimpleTipCalculator.Android.Resource.Id.HeaderSeparator;
			global::Intersoft.Crosslight.Android.Resource.Id.HeaderText = global::SimpleTipCalculator.Android.Resource.Id.HeaderText;
			global::Intersoft.Crosslight.Android.Resource.Id.ImagePlaceholder = global::SimpleTipCalculator.Android.Resource.Id.ImagePlaceholder;
			global::Intersoft.Crosslight.Android.Resource.Id.ImageView = global::SimpleTipCalculator.Android.Resource.Id.ImageView;
			global::Intersoft.Crosslight.Android.Resource.Id.InnerLayout = global::SimpleTipCalculator.Android.Resource.Id.InnerLayout;
			global::Intersoft.Crosslight.Android.Resource.Id.InternalSeekBar = global::SimpleTipCalculator.Android.Resource.Id.InternalSeekBar;
			global::Intersoft.Crosslight.Android.Resource.Id.SpinnerWidget = global::SimpleTipCalculator.Android.Resource.Id.SpinnerWidget;
			global::Intersoft.Crosslight.Android.Resource.Id.Switch = global::SimpleTipCalculator.Android.Resource.Id.Switch;
			global::Intersoft.Crosslight.Android.Resource.Id.TabContainer = global::SimpleTipCalculator.Android.Resource.Id.TabContainer;
			global::Intersoft.Crosslight.Android.Resource.Id.Text1 = global::SimpleTipCalculator.Android.Resource.Id.Text1;
			global::Intersoft.Crosslight.Android.Resource.Id.Text2 = global::SimpleTipCalculator.Android.Resource.Id.Text2;
			global::Intersoft.Crosslight.Android.Resource.Id.TimePickerWidget = global::SimpleTipCalculator.Android.Resource.Id.TimePickerWidget;
			global::Intersoft.Crosslight.Android.Resource.Id.TitleText = global::SimpleTipCalculator.Android.Resource.Id.TitleText;
			global::Intersoft.Crosslight.Android.Resource.Id.drawer_layout = global::SimpleTipCalculator.Android.Resource.Id.drawer_layout;
			global::Intersoft.Crosslight.Android.Resource.Id.fragmentBody = global::SimpleTipCalculator.Android.Resource.Id.fragmentBody;
			global::Intersoft.Crosslight.Android.Resource.Id.fragmentFooter = global::SimpleTipCalculator.Android.Resource.Id.fragmentFooter;
			global::Intersoft.Crosslight.Android.Resource.Id.fragmentHeader = global::SimpleTipCalculator.Android.Resource.Id.fragmentHeader;
			global::Intersoft.Crosslight.Android.Resource.Id.left_navdrawer = global::SimpleTipCalculator.Android.Resource.Id.left_navdrawer;
			global::Intersoft.Crosslight.Android.Resource.Id.listContainer = global::SimpleTipCalculator.Android.Resource.Id.listContainer;
			global::Intersoft.Crosslight.Android.Resource.Id.listFragmentFooter = global::SimpleTipCalculator.Android.Resource.Id.listFragmentFooter;
			global::Intersoft.Crosslight.Android.Resource.Id.listFragmentHeader = global::SimpleTipCalculator.Android.Resource.Id.listFragmentHeader;
			global::Intersoft.Crosslight.Android.Resource.Id.listFragmentLayout = global::SimpleTipCalculator.Android.Resource.Id.listFragmentLayout;
			global::Intersoft.Crosslight.Android.Resource.Id.maincontent_navdrawer = global::SimpleTipCalculator.Android.Resource.Id.maincontent_navdrawer;
			global::Intersoft.Crosslight.Android.Resource.Id.progressContainer = global::SimpleTipCalculator.Android.Resource.Id.progressContainer;
			global::Intersoft.Crosslight.Android.Resource.Id.progress_bar = global::SimpleTipCalculator.Android.Resource.Id.progress_bar;
			global::Intersoft.Crosslight.Android.Resource.Id.right_navdrawer = global::SimpleTipCalculator.Android.Resource.Id.right_navdrawer;
			global::Intersoft.Crosslight.Android.Resource.Interpolator.accelerate_quad = global::SimpleTipCalculator.Android.Resource.Interpolator.accelerate_quad;
			global::Intersoft.Crosslight.Android.Resource.Interpolator.decelerate_quad = global::SimpleTipCalculator.Android.Resource.Interpolator.decelerate_quad;
			global::Intersoft.Crosslight.Android.Resource.Layout.activitylargeindicator = global::SimpleTipCalculator.Android.Resource.Layout.activitylargeindicator;
			global::Intersoft.Crosslight.Android.Resource.Layout.activitysmallindicator = global::SimpleTipCalculator.Android.Resource.Layout.activitysmallindicator;
			global::Intersoft.Crosslight.Android.Resource.Layout.activitytranslucentindicator = global::SimpleTipCalculator.Android.Resource.Layout.activitytranslucentindicator;
			global::Intersoft.Crosslight.Android.Resource.Layout.buttonwidget = global::SimpleTipCalculator.Android.Resource.Layout.buttonwidget;
			global::Intersoft.Crosslight.Android.Resource.Layout.checkboxwidget = global::SimpleTipCalculator.Android.Resource.Layout.checkboxwidget;
			global::Intersoft.Crosslight.Android.Resource.Layout.datepickerwidget = global::SimpleTipCalculator.Android.Resource.Layout.datepickerwidget;
			global::Intersoft.Crosslight.Android.Resource.Layout.datetimepickerwidget = global::SimpleTipCalculator.Android.Resource.Layout.datetimepickerwidget;
			global::Intersoft.Crosslight.Android.Resource.Layout.formlayout = global::SimpleTipCalculator.Android.Resource.Layout.formlayout;
			global::Intersoft.Crosslight.Android.Resource.Layout.formlayoutdetailonly = global::SimpleTipCalculator.Android.Resource.Layout.formlayoutdetailonly;
			global::Intersoft.Crosslight.Android.Resource.Layout.formlayoutleftdetail = global::SimpleTipCalculator.Android.Resource.Layout.formlayoutleftdetail;
			global::Intersoft.Crosslight.Android.Resource.Layout.formlayoutrightdetail = global::SimpleTipCalculator.Android.Resource.Layout.formlayoutrightdetail;
			global::Intersoft.Crosslight.Android.Resource.Layout.formlayoutrowdetail = global::SimpleTipCalculator.Android.Resource.Layout.formlayoutrowdetail;
			global::Intersoft.Crosslight.Android.Resource.Layout.formsectionlayout = global::SimpleTipCalculator.Android.Resource.Layout.formsectionlayout;
			global::Intersoft.Crosslight.Android.Resource.Layout.imagepickerwidget = global::SimpleTipCalculator.Android.Resource.Layout.imagepickerwidget;
			global::Intersoft.Crosslight.Android.Resource.Layout.imageviewwidget = global::SimpleTipCalculator.Android.Resource.Layout.imageviewwidget;
			global::Intersoft.Crosslight.Android.Resource.Layout.listfragmentlayout = global::SimpleTipCalculator.Android.Resource.Layout.listfragmentlayout;
			global::Intersoft.Crosslight.Android.Resource.Layout.listgroupsectionheaderlayout = global::SimpleTipCalculator.Android.Resource.Layout.listgroupsectionheaderlayout;
			global::Intersoft.Crosslight.Android.Resource.Layout.listgroupsectionlayout = global::SimpleTipCalculator.Android.Resource.Layout.listgroupsectionlayout;
			global::Intersoft.Crosslight.Android.Resource.Layout.maincontainer = global::SimpleTipCalculator.Android.Resource.Layout.maincontainer;
			global::Intersoft.Crosslight.Android.Resource.Layout.navigationdrawerlayout = global::SimpleTipCalculator.Android.Resource.Layout.navigationdrawerlayout;
			global::Intersoft.Crosslight.Android.Resource.Layout.radiobuttonwidget = global::SimpleTipCalculator.Android.Resource.Layout.radiobuttonwidget;
			global::Intersoft.Crosslight.Android.Resource.Layout.sectionimageswithfieldslayout = global::SimpleTipCalculator.Android.Resource.Layout.sectionimageswithfieldslayout;
			global::Intersoft.Crosslight.Android.Resource.Layout.sectionlayout = global::SimpleTipCalculator.Android.Resource.Layout.sectionlayout;
			global::Intersoft.Crosslight.Android.Resource.Layout.seekbarwidget = global::SimpleTipCalculator.Android.Resource.Layout.seekbarwidget;
			global::Intersoft.Crosslight.Android.Resource.Layout.selectionwidget = global::SimpleTipCalculator.Android.Resource.Layout.selectionwidget;
			global::Intersoft.Crosslight.Android.Resource.Layout.spinnerdropdownitemlayout = global::SimpleTipCalculator.Android.Resource.Layout.spinnerdropdownitemlayout;
			global::Intersoft.Crosslight.Android.Resource.Layout.spinnerlayout = global::SimpleTipCalculator.Android.Resource.Layout.spinnerlayout;
			global::Intersoft.Crosslight.Android.Resource.Layout.spinnerwidget = global::SimpleTipCalculator.Android.Resource.Layout.spinnerwidget;
			global::Intersoft.Crosslight.Android.Resource.Layout.switchwidget = global::SimpleTipCalculator.Android.Resource.Layout.switchwidget;
			global::Intersoft.Crosslight.Android.Resource.Layout.tabcontainer = global::SimpleTipCalculator.Android.Resource.Layout.tabcontainer;
			global::Intersoft.Crosslight.Android.Resource.Layout.tablecellleftdetail = global::SimpleTipCalculator.Android.Resource.Layout.tablecellleftdetail;
			global::Intersoft.Crosslight.Android.Resource.Layout.tablecellrightdetail = global::SimpleTipCalculator.Android.Resource.Layout.tablecellrightdetail;
			global::Intersoft.Crosslight.Android.Resource.Layout.tablecellsubtitle = global::SimpleTipCalculator.Android.Resource.Layout.tablecellsubtitle;
			global::Intersoft.Crosslight.Android.Resource.Layout.tablecellsubtitlewithimage = global::SimpleTipCalculator.Android.Resource.Layout.tablecellsubtitlewithimage;
			global::Intersoft.Crosslight.Android.Resource.Layout.textfieldview = global::SimpleTipCalculator.Android.Resource.Layout.textfieldview;
			global::Intersoft.Crosslight.Android.Resource.Layout.timepickerwidget = global::SimpleTipCalculator.Android.Resource.Layout.timepickerwidget;
			global::Intersoft.Crosslight.Android.Resource.Layout.toast = global::SimpleTipCalculator.Android.Resource.Layout.toast;
			global::Intersoft.Crosslight.Android.Resource.Layout.toastlayout = global::SimpleTipCalculator.Android.Resource.Layout.toastlayout;
			global::Intersoft.Crosslight.Android.Resource.Layout.toastshadow = global::SimpleTipCalculator.Android.Resource.Layout.toastshadow;
			global::Intersoft.Crosslight.Android.Resource.Layout.toastshape = global::SimpleTipCalculator.Android.Resource.Layout.toastshape;
			global::Intersoft.Crosslight.Android.Resource.String.Add = global::SimpleTipCalculator.Android.Resource.String.Add;
			global::Intersoft.Crosslight.Android.Resource.String.Cancel = global::SimpleTipCalculator.Android.Resource.String.Cancel;
			global::Intersoft.Crosslight.Android.Resource.String.CheckAll = global::SimpleTipCalculator.Android.Resource.String.CheckAll;
			global::Intersoft.Crosslight.Android.Resource.String.ChooseFromGallery = global::SimpleTipCalculator.Android.Resource.String.ChooseFromGallery;
			global::Intersoft.Crosslight.Android.Resource.String.CloseDrawer = global::SimpleTipCalculator.Android.Resource.String.CloseDrawer;
			global::Intersoft.Crosslight.Android.Resource.String.Delete = global::SimpleTipCalculator.Android.Resource.String.Delete;
			global::Intersoft.Crosslight.Android.Resource.String.DeleteImage = global::SimpleTipCalculator.Android.Resource.String.DeleteImage;
			global::Intersoft.Crosslight.Android.Resource.String.More = global::SimpleTipCalculator.Android.Resource.String.More;
			global::Intersoft.Crosslight.Android.Resource.String.OpenDrawer = global::SimpleTipCalculator.Android.Resource.String.OpenDrawer;
			global::Intersoft.Crosslight.Android.Resource.String.Save = global::SimpleTipCalculator.Android.Resource.String.Save;
			global::Intersoft.Crosslight.Android.Resource.String.SelectImage = global::SimpleTipCalculator.Android.Resource.String.SelectImage;
			global::Intersoft.Crosslight.Android.Resource.String.TakePhoto = global::SimpleTipCalculator.Android.Resource.String.TakePhoto;
			global::Intersoft.Crosslight.Android.Resource.String.UncheckAll = global::SimpleTipCalculator.Android.Resource.String.UncheckAll;
			global::Intersoft.Crosslight.Android.Resource.Style.ListItem = global::SimpleTipCalculator.Android.Resource.Style.ListItem;
			global::Intersoft.Crosslight.Android.Resource.Style.TextAppearance_Small = global::SimpleTipCalculator.Android.Resource.Style.TextAppearance_Small;
			global::Intersoft.Crosslight.Android.Resource.Style.TextViewStyle = global::SimpleTipCalculator.Android.Resource.Style.TextViewStyle;
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f040000
			public const int toast_enter = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int toast_exit = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int transition_bottomtop = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int transition_fadein = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int transition_fadeout = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int transition_leftright = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int transition_rightleft = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int transition_topbottom = 2130968583;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f060000
			public const int select_dialog_items3 = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int select_image_dialog = 2131099649;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f070000
			public const int bright_foreground_dark = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int listviewbackgroundselector = 2131165185;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int btn_check_off_focused_holo_dark = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int btn_check_on_pressed_holo_dark = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ic_drawer = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int icon = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int leftdrawershadow = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int light_splash = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int rightdrawershadow = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int toast_frame_holo = 2130837511;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f0a0019
			public const int CalculateTipButton = 2131361817;
			
			// aapt resource value: 0x7f0a0022
			public const int ControlsPlaceholder = 2131361826;
			
			// aapt resource value: 0x7f0a0002
			public const int DatePickerWidget = 2131361794;
			
			// aapt resource value: 0x7f0a0003
			public const int DateTimePickerDateWidget = 2131361795;
			
			// aapt resource value: 0x7f0a0004
			public const int DateTimePickerTimeWidget = 2131361796;
			
			// aapt resource value: 0x7f0a0005
			public const int EditorContainer = 2131361797;
			
			// aapt resource value: 0x7f0a000b
			public const int FooterLayout = 2131361803;
			
			// aapt resource value: 0x7f0a000c
			public const int FooterText = 2131361804;
			
			// aapt resource value: 0x7f0a000a
			public const int FormContainer = 2131361802;
			
			// aapt resource value: 0x7f0a0007
			public const int HeaderLayout = 2131361799;
			
			// aapt resource value: 0x7f0a0009
			public const int HeaderSeparator = 2131361801;
			
			// aapt resource value: 0x7f0a0008
			public const int HeaderText = 2131361800;
			
			// aapt resource value: 0x7f0a0021
			public const int ImagePlaceholder = 2131361825;
			
			// aapt resource value: 0x7f0a0028
			public const int ImageView = 2131361832;
			
			// aapt resource value: 0x7f0a002a
			public const int InnerLayout = 2131361834;
			
			// aapt resource value: 0x7f0a0023
			public const int InternalSeekBar = 2131361827;
			
			// aapt resource value: 0x7f0a001c
			public const int LblPeople = 2131361820;
			
			// aapt resource value: 0x7f0a001a
			public const int LblTip = 2131361818;
			
			// aapt resource value: 0x7f0a001b
			public const int LblTotal = 2131361819;
			
			// aapt resource value: 0x7f0a0024
			public const int SpinnerWidget = 2131361828;
			
			// aapt resource value: 0x7f0a0025
			public const int Switch = 2131361829;
			
			// aapt resource value: 0x7f0a0026
			public const int TabContainer = 2131361830;
			
			// aapt resource value: 0x7f0a0001
			public const int Text1 = 2131361793;
			
			// aapt resource value: 0x7f0a0027
			public const int Text2 = 2131361831;
			
			// aapt resource value: 0x7f0a0029
			public const int TimePickerWidget = 2131361833;
			
			// aapt resource value: 0x7f0a0006
			public const int TitleText = 2131361798;
			
			// aapt resource value: 0x7f0a0015
			public const int TxtBill = 2131361813;
			
			// aapt resource value: 0x7f0a0018
			public const int TxtPeople = 2131361816;
			
			// aapt resource value: 0x7f0a0016
			public const int TxtTip = 2131361814;
			
			// aapt resource value: 0x7f0a001d
			public const int drawer_layout = 2131361821;
			
			// aapt resource value: 0x7f0a0013
			public const int fragmentBody = 2131361811;
			
			// aapt resource value: 0x7f0a0014
			public const int fragmentFooter = 2131361812;
			
			// aapt resource value: 0x7f0a0012
			public const int fragmentHeader = 2131361810;
			
			// aapt resource value: 0x7f0a001f
			public const int left_navdrawer = 2131361823;
			
			// aapt resource value: 0x7f0a0011
			public const int listContainer = 2131361809;
			
			// aapt resource value: 0x7f0a000f
			public const int listFragmentFooter = 2131361807;
			
			// aapt resource value: 0x7f0a000e
			public const int listFragmentHeader = 2131361806;
			
			// aapt resource value: 0x7f0a000d
			public const int listFragmentLayout = 2131361805;
			
			// aapt resource value: 0x7f0a001e
			public const int maincontent_navdrawer = 2131361822;
			
			// aapt resource value: 0x7f0a0010
			public const int progressContainer = 2131361808;
			
			// aapt resource value: 0x7f0a0000
			public const int progress_bar = 2131361792;
			
			// aapt resource value: 0x7f0a0020
			public const int right_navdrawer = 2131361824;
			
			// aapt resource value: 0x7f0a0017
			public const int tableRow = 2131361815;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Interpolator
		{
			
			// aapt resource value: 0x7f050000
			public const int accelerate_quad = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int decelerate_quad = 2131034113;
			
			static Interpolator()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Interpolator()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int activitylargeindicator = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int activitysmallindicator = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int activitytranslucentindicator = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int buttonwidget = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int checkboxwidget = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int datepickerwidget = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int datetimepickerwidget = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int formlayout = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int formlayoutdetailonly = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int formlayoutleftdetail = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int formlayoutrightdetail = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int formlayoutrowdetail = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int formsectionlayout = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int imagepickerwidget = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int imageviewwidget = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int listfragmentlayout = 2130903055;
			
			// aapt resource value: 0x7f030010
			public const int listgroupsectionheaderlayout = 2130903056;
			
			// aapt resource value: 0x7f030011
			public const int listgroupsectionlayout = 2130903057;
			
			// aapt resource value: 0x7f030012
			public const int maincontainer = 2130903058;
			
			// aapt resource value: 0x7f030013
			public const int MainLayout = 2130903059;
			
			// aapt resource value: 0x7f030014
			public const int navigationdrawerlayout = 2130903060;
			
			// aapt resource value: 0x7f030015
			public const int radiobuttonwidget = 2130903061;
			
			// aapt resource value: 0x7f030016
			public const int sectionimageswithfieldslayout = 2130903062;
			
			// aapt resource value: 0x7f030017
			public const int sectionlayout = 2130903063;
			
			// aapt resource value: 0x7f030018
			public const int seekbarwidget = 2130903064;
			
			// aapt resource value: 0x7f030019
			public const int selectionwidget = 2130903065;
			
			// aapt resource value: 0x7f03001a
			public const int spinnerdropdownitemlayout = 2130903066;
			
			// aapt resource value: 0x7f03001b
			public const int spinnerlayout = 2130903067;
			
			// aapt resource value: 0x7f03001c
			public const int spinnerwidget = 2130903068;
			
			// aapt resource value: 0x7f03001d
			public const int switchwidget = 2130903069;
			
			// aapt resource value: 0x7f03001e
			public const int tabcontainer = 2130903070;
			
			// aapt resource value: 0x7f03001f
			public const int tablecellleftdetail = 2130903071;
			
			// aapt resource value: 0x7f030020
			public const int tablecellrightdetail = 2130903072;
			
			// aapt resource value: 0x7f030021
			public const int tablecellsubtitle = 2130903073;
			
			// aapt resource value: 0x7f030022
			public const int tablecellsubtitlewithimage = 2130903074;
			
			// aapt resource value: 0x7f030023
			public const int textfieldview = 2130903075;
			
			// aapt resource value: 0x7f030024
			public const int timepickerwidget = 2130903076;
			
			// aapt resource value: 0x7f030025
			public const int toast = 2130903077;
			
			// aapt resource value: 0x7f030026
			public const int toastlayout = 2130903078;
			
			// aapt resource value: 0x7f030027
			public const int toastshadow = 2130903079;
			
			// aapt resource value: 0x7f030028
			public const int toastshape = 2130903080;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f080000
			public const int Add = 2131230720;
			
			// aapt resource value: 0x7f08000d
			public const int ApplicationName = 2131230733;
			
			// aapt resource value: 0x7f080001
			public const int Cancel = 2131230721;
			
			// aapt resource value: 0x7f080002
			public const int CheckAll = 2131230722;
			
			// aapt resource value: 0x7f080003
			public const int ChooseFromGallery = 2131230723;
			
			// aapt resource value: 0x7f080004
			public const int CloseDrawer = 2131230724;
			
			// aapt resource value: 0x7f080005
			public const int Delete = 2131230725;
			
			// aapt resource value: 0x7f080006
			public const int DeleteImage = 2131230726;
			
			// aapt resource value: 0x7f080007
			public const int More = 2131230727;
			
			// aapt resource value: 0x7f080008
			public const int OpenDrawer = 2131230728;
			
			// aapt resource value: 0x7f080009
			public const int Save = 2131230729;
			
			// aapt resource value: 0x7f08000a
			public const int SelectImage = 2131230730;
			
			// aapt resource value: 0x7f08000b
			public const int TakePhoto = 2131230731;
			
			// aapt resource value: 0x7f08000c
			public const int UncheckAll = 2131230732;
			
			// aapt resource value: 0x7f08000e
			public const int Update = 2131230734;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f090000
			public const int ListItem = 2131296256;
			
			// aapt resource value: 0x7f090001
			public const int TextAppearance_Small = 2131296257;
			
			// aapt resource value: 0x7f090002
			public const int TextViewStyle = 2131296258;
			
			// aapt resource value: 0x7f090003
			public const int Theme_Splash = 2131296259;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
